# Generated by Django 3.1.1 on 2020-10-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20201008_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageview',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
