# Generated by Django 3.1.1 on 2020-10-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerepo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=6)),
                ('title', models.TextField(default='')),
                ('sold', models.BooleanField(default=False)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cover', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
